name = "StanSample"
uuid = "c1514b29-d3a0-5178-b312-660c88baa699"
authors = ["Rob J Goedman <goedman@icloud.com>"]
version = "7.2.2"

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CompatHelperLocal = "5224ae11-6099-4aaa-941d-3aab004bd678"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
InferenceObjects = "b5cf5a8d-e756-4ee3-b014-01d49d192c00"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StanBase = "d0ee94f6-a23d-54aa-bbe9-7f572d6da7f5"
TableOperations = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
AxisKeys = "0.2"
BridgeStan = "1.0.1"
CSV = "0.10"
CompatHelperLocal = "0.1"
DataFrames = "1.3"
DelimitedFiles = "1.8, 1.9"
DocStringExtensions = "0.8, 0.9"
InferenceObjects = "0.3.2"
JSON = "0.21"
LazyArtifacts = "1.3"
MCMCChains = "5.6, 6"
MonteCarloMeasurements = "1.0"
NamedTupleTools = "0.14"
OrderedCollections = "1.4"
Parameters = "0.12"
Reexport = "1.2"
Requires = "1.3"
StanBase = "4.7.6"
TableOperations = "1.0"
Tables = "1.5"
julia = "1.8"

[extensions]
AxisKeysExt = "AxisKeys"
BridgeStanExt = "BridgeStan"
InferenceObjectsExt = "InferenceObjects"
MCMCChainsExt = "MCMCChains"
MonteCarloMeasurementsExt = "MonteCarloMeasurements"

[extras]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
InferenceObjects = "b5cf5a8d-e756-4ee3-b014-01d49d192c00"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AxisKeys", "BridgeStan", "Distributions", "Statistics", "LinearAlgebra", "MCMCChains",
    "MonteCarloMeasurements", "InferenceObjects", "StatsBase", "StatsFuns", "Test"]

[weakdeps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
InferenceObjects = "b5cf5a8d-e756-4ee3-b014-01d49d192c00"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"

