name = "StanSample"
uuid = "c1514b29-d3a0-5178-b312-660c88baa699"
authors = ["Rob J Goedman <goedman@icloud.com>"]
version = "1.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StanBase = "d0ee94f6-a23d-54aa-bbe9-7f572d6da7f5"
StanDump = "9713c8f3-0168-54b5-986e-22c526958f39"
StanRun = "d49c3b98-12bb-537a-8c40-37c13654c7f4"
StanSamples = "52d0d7a9-b304-5f31-a727-b234d0b606ff"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
CSV = "^0.5"
DataFrames = "^0.19"
DocStringExtensions = "^0.8"
MCMCChains = "^0.3"
NamedTupleTools = "^0.11, ^0.12"
Parameters = "^0.12"
Reexport = "0.2"
StanBase = "^1.0"
StanDump = "0.2"
StanRun = "0.2"
StanSamples = "^0.1"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
