name = "StanRun"
uuid = "d49c3b98-12bb-537a-8c40-37c13654c7f4"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StanDump = "9713c8f3-0168-54b5-986e-22c526958f39"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
