name = "StanSample"
uuid = "c1514b29-d3a0-5178-b312-660c88baa699"
authors = ["Rob J Goedman <goedman@icloud.com>"]
version = "1.1.5"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
StanBase = "d0ee94f6-a23d-54aa-bbe9-7f572d6da7f5"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
CSV = "0.5"
DataFrames = "0.20"
DocStringExtensions = "0.8"
Documenter = "0.24"
MCMCChains = "1.0"
StanBase = "1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
